name: thebibleapp
description: A new Flutter project.

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_icons: ^1.0.0+1
  google_mobile_ads: ^0.11.0+3
  get: ^3.26.0
  hive: ^1.4.1+1
  intl: ^0.16.0
  loading_animations: ^2.1.0
  package_info: ^0.4.0+16
  path_provider: ^2.0.1
  provider: ^5.0.0
  sqflite: ^2.0.0+2
  url_launcher: ^5.4.2
  uuid: ^2.0.4
  social_share: ^2.1.1
  flutter_rating_bar: ^4.0.0
  rate_my_app: ^1.1.1
  google_fonts: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.7.4
flutter_icons:
  image_path: "assets/icon/icon.jpg"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/databases/
    - assets/icon/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-Italic.ttf
